// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooApp.data;

#nullable disable

namespace ZooApp.Migrations
{
    [DbContext(typeof(ZooAppContext))]
    [Migration("20240529180644_IMageUpload")]
    partial class IMageUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ZooApp.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Diet")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnimalId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Animal", (string)null);

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            Diet = 0,
                            EmployeeId = 1,
                            EnclosureId = 1,
                            Name = "Lion",
                            Sex = 0,
                            Species = "Panthera leo"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 10,
                            Diet = 2,
                            EmployeeId = 2,
                            EnclosureId = 2,
                            Name = "Elephant",
                            Sex = 1,
                            Species = "Loxodonta africana"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 3,
                            Diet = 1,
                            EmployeeId = 5,
                            EnclosureId = 5,
                            Name = "Parrot",
                            Sex = 1,
                            Species = "Psittaciformes"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 6,
                            Diet = 0,
                            EmployeeId = 3,
                            EnclosureId = 1,
                            Name = "Tiger",
                            Sex = 1,
                            Species = "Panthera tigris"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 12,
                            Diet = 1,
                            EmployeeId = 4,
                            EnclosureId = 2,
                            Name = "Gorilla",
                            Sex = 0,
                            Species = "Gorilla gorilla"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 5,
                            Diet = 3,
                            EmployeeId = 5,
                            EnclosureId = 6,
                            Name = "Penguin",
                            Sex = 0,
                            Species = "Aptenodytes forsteri"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 4,
                            Diet = 2,
                            EmployeeId = 6,
                            EnclosureId = 3,
                            Name = "Kangaroo",
                            Sex = 1,
                            Species = "Macropus"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 10,
                            Diet = 0,
                            EmployeeId = 3,
                            EnclosureId = 4,
                            Name = "Crocodile",
                            Sex = 0,
                            Species = "Crocodylus"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 7,
                            Diet = 2,
                            EmployeeId = 4,
                            EnclosureId = 1,
                            Name = "Zebra",
                            Sex = 1,
                            Species = "Equus zebra"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 9,
                            Diet = 2,
                            EmployeeId = 5,
                            EnclosureId = 2,
                            Name = "Panda",
                            Sex = 0,
                            Species = "Ailuropoda melanoleuca"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 8,
                            Diet = 2,
                            EmployeeId = 6,
                            EnclosureId = 3,
                            Name = "Giraffe",
                            Sex = 1,
                            Species = "Giraffa"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 4,
                            Diet = 1,
                            EmployeeId = 3,
                            EnclosureId = 4,
                            Name = "Lemur",
                            Sex = 0,
                            Species = "Lemur"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 11,
                            Diet = 0,
                            EmployeeId = 4,
                            EnclosureId = 6,
                            Name = "Polar Bear",
                            Sex = 1,
                            Species = "Ursus maritimus"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 6,
                            Diet = 2,
                            EmployeeId = 5,
                            EnclosureId = 2,
                            Name = "Hippo",
                            Sex = 0,
                            Species = "Hippopotamus"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 5,
                            Diet = 2,
                            EmployeeId = 6,
                            EnclosureId = 4,
                            Name = "Sloth",
                            Sex = 1,
                            Species = "Bradypus"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 8,
                            Diet = 0,
                            EmployeeId = 3,
                            EnclosureId = 3,
                            Name = "Wolf",
                            Sex = 0,
                            Species = "Canis lupus"
                        });
                });

            modelBuilder.Entity("ZooApp.Models.AnimalEmployee", b =>
                {
                    b.Property<int>("AnimalEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalEmployeeId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("AnimalEmployeeId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AnimalEmployee", (string)null);

                    b.HasData(
                        new
                        {
                            AnimalEmployeeId = 1,
                            AnimalId = 1,
                            EmployeeId = 1
                        },
                        new
                        {
                            AnimalEmployeeId = 2,
                            AnimalId = 2,
                            EmployeeId = 2
                        },
                        new
                        {
                            AnimalEmployeeId = 3,
                            AnimalId = 3,
                            EmployeeId = 5
                        },
                        new
                        {
                            AnimalEmployeeId = 4,
                            AnimalId = 4,
                            EmployeeId = 3
                        },
                        new
                        {
                            AnimalEmployeeId = 5,
                            AnimalId = 5,
                            EmployeeId = 4
                        },
                        new
                        {
                            AnimalEmployeeId = 6,
                            AnimalId = 6,
                            EmployeeId = 5
                        },
                        new
                        {
                            AnimalEmployeeId = 7,
                            AnimalId = 7,
                            EmployeeId = 6
                        },
                        new
                        {
                            AnimalEmployeeId = 8,
                            AnimalId = 8,
                            EmployeeId = 3
                        },
                        new
                        {
                            AnimalEmployeeId = 9,
                            AnimalId = 9,
                            EmployeeId = 4
                        },
                        new
                        {
                            AnimalEmployeeId = 10,
                            AnimalId = 10,
                            EmployeeId = 5
                        },
                        new
                        {
                            AnimalEmployeeId = 11,
                            AnimalId = 11,
                            EmployeeId = 6
                        },
                        new
                        {
                            AnimalEmployeeId = 12,
                            AnimalId = 12,
                            EmployeeId = 3
                        },
                        new
                        {
                            AnimalEmployeeId = 13,
                            AnimalId = 13,
                            EmployeeId = 4
                        },
                        new
                        {
                            AnimalEmployeeId = 14,
                            AnimalId = 14,
                            EmployeeId = 5
                        },
                        new
                        {
                            AnimalEmployeeId = 15,
                            AnimalId = 15,
                            EmployeeId = 6
                        },
                        new
                        {
                            AnimalEmployeeId = 16,
                            AnimalId = 16,
                            EmployeeId = 3
                        });
                });

            modelBuilder.Entity("ZooApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EnclosureId = 1,
                            HireDate = new DateTime(2024, 4, 30, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7210),
                            Name = "John Doe",
                            Phone = "123-456-7890",
                            Role = 0,
                            Salary = 50000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            EnclosureId = 2,
                            HireDate = new DateTime(2024, 5, 10, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7213),
                            Name = "Jane Smith",
                            Phone = "987-654-3210",
                            Role = 1,
                            Salary = 70000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            EnclosureId = 3,
                            HireDate = new DateTime(2024, 5, 5, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7216),
                            Name = "Michael Johnson",
                            Phone = "111-222-3333",
                            Role = 0,
                            Salary = 55000m
                        },
                        new
                        {
                            EmployeeId = 4,
                            EnclosureId = 4,
                            HireDate = new DateTime(2024, 5, 15, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7218),
                            Name = "Emily Wilson",
                            Phone = "444-555-6666",
                            Role = 1,
                            Salary = 72000m
                        },
                        new
                        {
                            EmployeeId = 5,
                            EnclosureId = 5,
                            HireDate = new DateTime(2024, 5, 2, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7220),
                            Name = "Christopher Lee",
                            Phone = "777-888-9999",
                            Role = 0,
                            Salary = 52000m
                        },
                        new
                        {
                            EmployeeId = 6,
                            EnclosureId = 6,
                            HireDate = new DateTime(2024, 5, 20, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7222),
                            Name = "Jessica Brown",
                            Phone = "999-888-7777",
                            Role = 1,
                            Salary = 73000m
                        });
                });

            modelBuilder.Entity("ZooApp.Models.Enclosure", b =>
                {
                    b.Property<int>("EnclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnclosureId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EnclosureId");

                    b.ToTable("Enclosure", (string)null);

                    b.HasData(
                        new
                        {
                            EnclosureId = 1,
                            Capacity = 5,
                            Habitat = "Savannah",
                            Name = "Savannah Enclosure"
                        },
                        new
                        {
                            EnclosureId = 2,
                            Capacity = 10,
                            Habitat = "Jungle",
                            Name = "Jungle Enclosure"
                        },
                        new
                        {
                            EnclosureId = 3,
                            Capacity = 7,
                            Habitat = "Forest",
                            Name = "Forest Enclosure"
                        },
                        new
                        {
                            EnclosureId = 4,
                            Capacity = 6,
                            Habitat = "River",
                            Name = "River Enclosure"
                        },
                        new
                        {
                            EnclosureId = 5,
                            Capacity = 8,
                            Habitat = "Aviary",
                            Name = "Aviary Enclosure"
                        },
                        new
                        {
                            EnclosureId = 6,
                            Capacity = 5,
                            Habitat = "Arctic",
                            Name = "Arctic Enclosure"
                        });
                });

            modelBuilder.Entity("ZooApp.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EventId");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Date = new DateTime(2024, 6, 9, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7041),
                            Description = "Guided safari tour through the zoo",
                            ImageFileName = "HI",
                            Name = "Zoo Safari",
                            TicketPrice = 25m
                        },
                        new
                        {
                            EventId = 2,
                            Date = new DateTime(2024, 6, 16, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7089),
                            Description = "Educational talk on wildlife conservation",
                            ImageFileName = "HI",
                            Name = "Wildlife Conservation Talk",
                            TicketPrice = 10m
                        },
                        new
                        {
                            EventId = 3,
                            Date = new DateTime(2024, 6, 24, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7095),
                            Description = "Experience the zoo after dark with special activities and tours",
                            ImageFileName = "HI",
                            Name = "Night at the Zoo",
                            TicketPrice = 30m
                        },
                        new
                        {
                            EventId = 4,
                            Date = new DateTime(2024, 6, 29, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7098),
                            Description = "Guided tour focusing on observing various bird species in the zoo",
                            ImageFileName = "HI",
                            Name = "Bird Watching Tour",
                            TicketPrice = 15m
                        },
                        new
                        {
                            EventId = 5,
                            Date = new DateTime(2024, 7, 9, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7100),
                            Description = "Learn about animal diets and behavior during feeding time",
                            ImageFileName = "HI",
                            Name = "Animal Feeding Demonstration",
                            TicketPrice = 20m
                        });
                });

            modelBuilder.Entity("ZooApp.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("EventId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Ticket", (string)null);

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            DateOfPurchase = new DateTime(2024, 5, 28, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7369),
                            EventId = 1,
                            VisitorId = 1
                        },
                        new
                        {
                            TicketId = 2,
                            DateOfPurchase = new DateTime(2024, 5, 29, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7371),
                            EventId = 2,
                            VisitorId = 2
                        },
                        new
                        {
                            TicketId = 3,
                            DateOfPurchase = new DateTime(2024, 5, 27, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7373),
                            EventId = 1,
                            VisitorId = 3
                        },
                        new
                        {
                            TicketId = 4,
                            DateOfPurchase = new DateTime(2024, 5, 26, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7375),
                            EventId = 2,
                            VisitorId = 4
                        },
                        new
                        {
                            TicketId = 5,
                            DateOfPurchase = new DateTime(2024, 5, 25, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7376),
                            EventId = 1,
                            VisitorId = 5
                        },
                        new
                        {
                            TicketId = 6,
                            DateOfPurchase = new DateTime(2024, 5, 24, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7378),
                            EventId = 2,
                            VisitorId = 6
                        },
                        new
                        {
                            TicketId = 7,
                            DateOfPurchase = new DateTime(2024, 5, 23, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7380),
                            EventId = 1,
                            VisitorId = 7
                        },
                        new
                        {
                            TicketId = 8,
                            DateOfPurchase = new DateTime(2024, 5, 22, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7381),
                            EventId = 2,
                            VisitorId = 8
                        },
                        new
                        {
                            TicketId = 9,
                            DateOfPurchase = new DateTime(2024, 5, 21, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7383),
                            EventId = 1,
                            VisitorId = 9
                        },
                        new
                        {
                            TicketId = 10,
                            DateOfPurchase = new DateTime(2024, 5, 20, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7384),
                            EventId = 2,
                            VisitorId = 10
                        },
                        new
                        {
                            TicketId = 11,
                            DateOfPurchase = new DateTime(2024, 5, 19, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7386),
                            EventId = 1,
                            VisitorId = 11
                        },
                        new
                        {
                            TicketId = 12,
                            DateOfPurchase = new DateTime(2024, 5, 18, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7387),
                            EventId = 2,
                            VisitorId = 12
                        },
                        new
                        {
                            TicketId = 13,
                            DateOfPurchase = new DateTime(2024, 5, 17, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7389),
                            EventId = 1,
                            VisitorId = 13
                        },
                        new
                        {
                            TicketId = 14,
                            DateOfPurchase = new DateTime(2024, 5, 16, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7390),
                            EventId = 2,
                            VisitorId = 14
                        },
                        new
                        {
                            TicketId = 15,
                            DateOfPurchase = new DateTime(2024, 5, 15, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7392),
                            EventId = 1,
                            VisitorId = 15
                        },
                        new
                        {
                            TicketId = 16,
                            DateOfPurchase = new DateTime(2024, 5, 14, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7393),
                            EventId = 2,
                            VisitorId = 16
                        },
                        new
                        {
                            TicketId = 17,
                            DateOfPurchase = new DateTime(2024, 5, 13, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7395),
                            EventId = 1,
                            VisitorId = 17
                        });
                });

            modelBuilder.Entity("ZooApp.Models.Visitor", b =>
                {
                    b.Property<int>("VisitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorId");

                    b.ToTable("Visitor", (string)null);

                    b.HasData(
                        new
                        {
                            VisitorId = 1,
                            Address = "123 Main St",
                            Email = "alice@example.com",
                            Name = "Alice",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            VisitorId = 2,
                            Address = "456 Elm St",
                            Email = "bob@example.com",
                            Name = "Bob",
                            Phone = "987-654-3210"
                        },
                        new
                        {
                            VisitorId = 3,
                            Address = "789 Oak St",
                            Email = "eva@example.com",
                            Name = "Eva Martinez",
                            Phone = "111-111-1111"
                        },
                        new
                        {
                            VisitorId = 4,
                            Address = "101 Pine St",
                            Email = "david@example.com",
                            Name = "David Brown",
                            Phone = "222-222-2222"
                        },
                        new
                        {
                            VisitorId = 5,
                            Address = "456 Maple Ave",
                            Email = "sophia@example.com",
                            Name = "Sophia Garcia",
                            Phone = "333-333-3333"
                        },
                        new
                        {
                            VisitorId = 6,
                            Address = "789 Elm St",
                            Email = "liam@example.com",
                            Name = "Liam Rodriguez",
                            Phone = "444-444-4444"
                        },
                        new
                        {
                            VisitorId = 7,
                            Address = "123 Oak St",
                            Email = "olivia@example.com",
                            Name = "Olivia Hernandez",
                            Phone = "555-555-5555"
                        },
                        new
                        {
                            VisitorId = 8,
                            Address = "789 Pine Ave",
                            Email = "lucas@example.com",
                            Name = "Lucas Martinez",
                            Phone = "666-666-6666"
                        },
                        new
                        {
                            VisitorId = 9,
                            Address = "101 Maple St",
                            Email = "isabella@example.com",
                            Name = "Isabella Nguyen",
                            Phone = "777-777-7777"
                        },
                        new
                        {
                            VisitorId = 10,
                            Address = "456 Oak Ave",
                            Email = "mia@example.com",
                            Name = "Mia Kim",
                            Phone = "888-888-8888"
                        },
                        new
                        {
                            VisitorId = 11,
                            Address = "123 Maple Ave",
                            Email = "james@example.com",
                            Name = "James Smith",
                            Phone = "999-999-9999"
                        },
                        new
                        {
                            VisitorId = 12,
                            Address = "789 Pine St",
                            Email = "charlotte@example.com",
                            Name = "Charlotte Johnson",
                            Phone = "101-101-1010"
                        },
                        new
                        {
                            VisitorId = 13,
                            Address = "456 Elm St",
                            Email = "william@example.com",
                            Name = "William Brown",
                            Phone = "202-202-2020"
                        },
                        new
                        {
                            VisitorId = 14,
                            Address = "123 Maple Ave",
                            Email = "amelia@example.com",
                            Name = "Amelia Davis",
                            Phone = "303-303-3030"
                        },
                        new
                        {
                            VisitorId = 15,
                            Address = "789 Elm Ave",
                            Email = "benjamin@example.com",
                            Name = "Benjamin Wilson",
                            Phone = "404-404-4040"
                        },
                        new
                        {
                            VisitorId = 16,
                            Address = "101 Oak St",
                            Email = "emma@example.com",
                            Name = "Emma Rodriguez",
                            Phone = "505-505-5050"
                        },
                        new
                        {
                            VisitorId = 17,
                            Address = "456 Pine Ave",
                            Email = "alexander@example.com",
                            Name = "Alexander Garcia",
                            Phone = "606-606-6060"
                        });
                });

            modelBuilder.Entity("ZooApp.Models.VisitorEventAttendance", b =>
                {
                    b.Property<int>("VisitorEventAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorEventAttendanceId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("VisitorEventAttendanceId");

                    b.HasIndex("EventId");

                    b.HasIndex("VisitorId");

                    b.ToTable("VisitorEventAttendance", (string)null);

                    b.HasData(
                        new
                        {
                            VisitorEventAttendanceId = 1,
                            EventId = 1,
                            VisitorId = 1
                        },
                        new
                        {
                            VisitorEventAttendanceId = 2,
                            EventId = 2,
                            VisitorId = 2
                        },
                        new
                        {
                            VisitorEventAttendanceId = 3,
                            EventId = 3,
                            VisitorId = 3
                        },
                        new
                        {
                            VisitorEventAttendanceId = 4,
                            EventId = 4,
                            VisitorId = 4
                        },
                        new
                        {
                            VisitorEventAttendanceId = 5,
                            EventId = 5,
                            VisitorId = 5
                        },
                        new
                        {
                            VisitorEventAttendanceId = 6,
                            EventId = 1,
                            VisitorId = 6
                        },
                        new
                        {
                            VisitorEventAttendanceId = 7,
                            EventId = 2,
                            VisitorId = 7
                        },
                        new
                        {
                            VisitorEventAttendanceId = 8,
                            EventId = 3,
                            VisitorId = 8
                        },
                        new
                        {
                            VisitorEventAttendanceId = 9,
                            EventId = 4,
                            VisitorId = 9
                        },
                        new
                        {
                            VisitorEventAttendanceId = 10,
                            EventId = 5,
                            VisitorId = 10
                        },
                        new
                        {
                            VisitorEventAttendanceId = 11,
                            EventId = 3,
                            VisitorId = 11
                        },
                        new
                        {
                            VisitorEventAttendanceId = 12,
                            EventId = 4,
                            VisitorId = 12
                        },
                        new
                        {
                            VisitorEventAttendanceId = 13,
                            EventId = 5,
                            VisitorId = 13
                        },
                        new
                        {
                            VisitorEventAttendanceId = 14,
                            EventId = 1,
                            VisitorId = 14
                        },
                        new
                        {
                            VisitorEventAttendanceId = 15,
                            EventId = 2,
                            VisitorId = 15
                        },
                        new
                        {
                            VisitorEventAttendanceId = 16,
                            EventId = 3,
                            VisitorId = 16
                        },
                        new
                        {
                            VisitorEventAttendanceId = 17,
                            EventId = 4,
                            VisitorId = 17
                        });
                });

            modelBuilder.Entity("ZooApp.Models.VisitorLog", b =>
                {
                    b.Property<int>("VisitorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorLogId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateVisited")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("VisitorLogId");

                    b.HasIndex("VisitorId");

                    b.ToTable("VisitorLog", (string)null);

                    b.HasData(
                        new
                        {
                            VisitorLogId = 1,
                            Comments = "Enjoyed the zoo!",
                            DateVisited = new DateTime(2024, 5, 28, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7478),
                            VisitorId = 1
                        },
                        new
                        {
                            VisitorLogId = 2,
                            Comments = "Great experience!",
                            DateVisited = new DateTime(2024, 5, 29, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7480),
                            VisitorId = 2
                        },
                        new
                        {
                            VisitorLogId = 3,
                            Comments = "Had a wonderful time with family!",
                            DateVisited = new DateTime(2024, 5, 27, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7482),
                            VisitorId = 3
                        },
                        new
                        {
                            VisitorLogId = 4,
                            Comments = "Educational and fun!",
                            DateVisited = new DateTime(2024, 5, 26, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7484),
                            VisitorId = 4
                        },
                        new
                        {
                            VisitorLogId = 5,
                            Comments = "Loved the animal exhibits!",
                            DateVisited = new DateTime(2024, 5, 25, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7485),
                            VisitorId = 5
                        },
                        new
                        {
                            VisitorLogId = 6,
                            Comments = "Amazing zoo experience!",
                            DateVisited = new DateTime(2024, 5, 24, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7487),
                            VisitorId = 6
                        },
                        new
                        {
                            VisitorLogId = 7,
                            Comments = "Fantastic day out!",
                            DateVisited = new DateTime(2024, 5, 23, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7488),
                            VisitorId = 7
                        },
                        new
                        {
                            VisitorLogId = 8,
                            Comments = "Will visit again soon!",
                            DateVisited = new DateTime(2024, 5, 22, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7490),
                            VisitorId = 8
                        },
                        new
                        {
                            VisitorLogId = 9,
                            Comments = "Kids loved the animals!",
                            DateVisited = new DateTime(2024, 5, 21, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7492),
                            VisitorId = 9
                        },
                        new
                        {
                            VisitorLogId = 10,
                            Comments = "Highly recommended!",
                            DateVisited = new DateTime(2024, 5, 20, 6, 6, 43, 878, DateTimeKind.Local).AddTicks(7493),
                            VisitorId = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooApp.Models.Animal", b =>
                {
                    b.HasOne("ZooApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooApp.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("ZooApp.Models.AnimalEmployee", b =>
                {
                    b.HasOne("ZooApp.Models.Animal", "Animal")
                        .WithMany("AnimalZooEmployees")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooApp.Models.Employee", "Employee")
                        .WithMany("AnimalEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ZooApp.Models.Employee", b =>
                {
                    b.HasOne("ZooApp.Models.Enclosure", "Enclosure")
                        .WithMany("Employees")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("ZooApp.Models.Ticket", b =>
                {
                    b.HasOne("ZooApp.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooApp.Models.Visitor", "Visitor")
                        .WithMany("Tickets")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ZooApp.Models.VisitorEventAttendance", b =>
                {
                    b.HasOne("ZooApp.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooApp.Models.Visitor", "Visitor")
                        .WithMany("EventAttendances")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ZooApp.Models.VisitorLog", b =>
                {
                    b.HasOne("ZooApp.Models.Visitor", "Visitor")
                        .WithMany("VisitorLogs")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ZooApp.Models.Animal", b =>
                {
                    b.Navigation("AnimalZooEmployees");
                });

            modelBuilder.Entity("ZooApp.Models.Employee", b =>
                {
                    b.Navigation("AnimalEmployees");
                });

            modelBuilder.Entity("ZooApp.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ZooApp.Models.Visitor", b =>
                {
                    b.Navigation("EventAttendances");

                    b.Navigation("Tickets");

                    b.Navigation("VisitorLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
